######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 16 19:15:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= app_bundle
QT += webkit

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += ebe.qrc
