#############################################################################
# Makefile for building: qtebe
# Generated by qmake (2.01a) (Qt 4.8.3) on: Wed Dec 5 21:13:52 2012
# Project:  qtebe.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile qtebe.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/clang
CXX           = /usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-g++ -I. -I. -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I. -I/opt/local/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/include -F/opt/local/Library/Frameworks -F/opt/local/lib
LINK          = /usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.8
LIBS          = $(SUBLIBS) -F/opt/local/Library/Frameworks -F/opt/local/lib  -F/opt/local/Library/Frameworks -F/opt/local/lib -L/opt/local/lib -framework QtWebKit -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.8

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sourcewindow.cpp \
		mainwindow.cpp \
		commandline.cpp \
		sourceframe.cpp \
		terminalwindow.cpp \
		registerwindow.cpp \
		consolewindow.cpp \
		projectwindow.cpp \
		datawindow.cpp \
		floatwindow.cpp \
		settings.cpp \
		listwidget.cpp \
		stylesheet.cpp moc_mainwindow.cpp \
		moc_sourcewindow.cpp \
		moc_commandline.cpp \
		moc_sourceframe.cpp \
		moc_terminalwindow.cpp \
		moc_registerwindow.cpp \
		moc_consolewindow.cpp \
		moc_projectwindow.cpp \
		moc_datawindow.cpp \
		moc_floatwindow.cpp \
		moc_settings.cpp \
		moc_listwidget.cpp \
		qrc_ebe.cpp
OBJECTS       = main.o \
		sourcewindow.o \
		mainwindow.o \
		commandline.o \
		sourceframe.o \
		terminalwindow.o \
		registerwindow.o \
		consolewindow.o \
		projectwindow.o \
		datawindow.o \
		floatwindow.o \
		settings.o \
		listwidget.o \
		stylesheet.o \
		moc_mainwindow.o \
		moc_sourcewindow.o \
		moc_commandline.o \
		moc_sourceframe.o \
		moc_terminalwindow.o \
		moc_registerwindow.o \
		moc_consolewindow.o \
		moc_projectwindow.o \
		moc_datawindow.o \
		moc_floatwindow.o \
		moc_settings.o \
		moc_listwidget.o \
		qrc_ebe.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		qtebe.pro
QMAKE_TARGET  = qtebe
DESTDIR       = 
TARGET        = qtebe

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.8 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtebe.pro  /opt/local/share/qt4/mkspecs/macx-g++/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/Library/Frameworks/QtWebKit.framework/QtWebKit.prl \
		/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile qtebe.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf:
/opt/local/share/qt4/mkspecs/common/g++-base.conf:
/opt/local/share/qt4/mkspecs/common/g++-macx.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/Library/Frameworks/QtWebKit.framework/QtWebKit.prl:
/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtebe.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtebe1.0.0 || $(MKDIR) .tmp/qtebe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtebe1.0.0/ && $(COPY_FILE) --parents mainwindow.h sourcewindow.h commandline.h sourceframe.h terminalwindow.h registerwindow.h consolewindow.h projectwindow.h datawindow.h floatwindow.h settings.h listwidget.h stylesheet.h .tmp/qtebe1.0.0/ && $(COPY_FILE) --parents ebe.qrc .tmp/qtebe1.0.0/ && $(COPY_FILE) --parents main.cpp sourcewindow.cpp mainwindow.cpp commandline.cpp sourceframe.cpp terminalwindow.cpp registerwindow.cpp consolewindow.cpp projectwindow.cpp datawindow.cpp floatwindow.cpp settings.cpp listwidget.cpp stylesheet.cpp .tmp/qtebe1.0.0/ && (cd `dirname .tmp/qtebe1.0.0` && $(TAR) qtebe1.0.0.tar qtebe1.0.0 && $(COMPRESS) qtebe1.0.0.tar) && $(MOVE) `dirname .tmp/qtebe1.0.0`/qtebe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtebe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_sourcewindow.cpp moc_commandline.cpp moc_sourceframe.cpp moc_terminalwindow.cpp moc_registerwindow.cpp moc_consolewindow.cpp moc_projectwindow.cpp moc_datawindow.cpp moc_floatwindow.cpp moc_settings.cpp moc_listwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sourcewindow.cpp moc_commandline.cpp moc_sourceframe.cpp moc_terminalwindow.cpp moc_registerwindow.cpp moc_consolewindow.cpp moc_projectwindow.cpp moc_datawindow.cpp moc_floatwindow.cpp moc_settings.cpp moc_listwidget.cpp
moc_mainwindow.cpp: datawindow.h \
		sourceframe.h \
		registerwindow.h \
		floatwindow.h \
		terminalwindow.h \
		consolewindow.h \
		projectwindow.h \
		settings.h \
		mainwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_sourcewindow.cpp: sourcewindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sourcewindow.h -o moc_sourcewindow.cpp

moc_commandline.cpp: commandline.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ commandline.h -o moc_commandline.cpp

moc_sourceframe.cpp: sourceframe.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sourceframe.h -o moc_sourceframe.cpp

moc_terminalwindow.cpp: terminalwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ terminalwindow.h -o moc_terminalwindow.cpp

moc_registerwindow.cpp: registerwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ registerwindow.h -o moc_registerwindow.cpp

moc_consolewindow.cpp: consolewindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ consolewindow.h -o moc_consolewindow.cpp

moc_projectwindow.cpp: projectwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ projectwindow.h -o moc_projectwindow.cpp

moc_datawindow.cpp: datawindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ datawindow.h -o moc_datawindow.cpp

moc_floatwindow.cpp: floatwindow.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ floatwindow.h -o moc_floatwindow.cpp

moc_settings.cpp: settings.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ settings.h -o moc_settings.cpp

moc_listwidget.cpp: listwidget.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ listwidget.h -o moc_listwidget.cpp

compiler_rcc_make_all: qrc_ebe.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ebe.cpp
qrc_ebe.cpp: ebe.qrc \
		html/editing.html \
		html/about.html \
		html/breakpoints.html \
		html/projects.html \
		html/start.html \
		html/running.html \
		images/ebe64.png
	/opt/local/bin/rcc -name ebe ebe.qrc -o qrc_ebe.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		datawindow.h \
		sourceframe.h \
		registerwindow.h \
		floatwindow.h \
		terminalwindow.h \
		consolewindow.h \
		projectwindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sourcewindow.o: sourcewindow.cpp sourcewindow.h \
		stylesheet.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sourcewindow.o sourcewindow.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		datawindow.h \
		sourceframe.h \
		registerwindow.h \
		floatwindow.h \
		terminalwindow.h \
		consolewindow.h \
		projectwindow.h \
		settings.h \
		stylesheet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

commandline.o: commandline.cpp commandline.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandline.o commandline.cpp

sourceframe.o: sourceframe.cpp sourceframe.h \
		sourcewindow.h \
		commandline.h \
		stylesheet.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sourceframe.o sourceframe.cpp

terminalwindow.o: terminalwindow.cpp terminalwindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terminalwindow.o terminalwindow.cpp

registerwindow.o: registerwindow.cpp registerwindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registerwindow.o registerwindow.cpp

consolewindow.o: consolewindow.cpp consolewindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o consolewindow.o consolewindow.cpp

projectwindow.o: projectwindow.cpp projectwindow.h \
		sourceframe.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectwindow.o projectwindow.cpp

datawindow.o: datawindow.cpp datawindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datawindow.o datawindow.cpp

floatwindow.o: floatwindow.cpp floatwindow.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o floatwindow.o floatwindow.cpp

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

listwidget.o: listwidget.cpp listwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listwidget.o listwidget.cpp

stylesheet.o: stylesheet.cpp stylesheet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stylesheet.o stylesheet.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sourcewindow.o: moc_sourcewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sourcewindow.o moc_sourcewindow.cpp

moc_commandline.o: moc_commandline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commandline.o moc_commandline.cpp

moc_sourceframe.o: moc_sourceframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sourceframe.o moc_sourceframe.cpp

moc_terminalwindow.o: moc_terminalwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_terminalwindow.o moc_terminalwindow.cpp

moc_registerwindow.o: moc_registerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registerwindow.o moc_registerwindow.cpp

moc_consolewindow.o: moc_consolewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_consolewindow.o moc_consolewindow.cpp

moc_projectwindow.o: moc_projectwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectwindow.o moc_projectwindow.cpp

moc_datawindow.o: moc_datawindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datawindow.o moc_datawindow.cpp

moc_floatwindow.o: moc_floatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_floatwindow.o moc_floatwindow.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_listwidget.o: moc_listwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listwidget.o moc_listwidget.cpp

qrc_ebe.o: qrc_ebe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ebe.o qrc_ebe.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

