######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 18 14:35:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= app_bundle
QT += webkit

# Input
HEADERS += mainwindow.h sourcewindow.h commandline.h
SOURCES += main.cpp mainwindow.cpp sourcewindow.cpp commandline.cpp
RESOURCES += ebe.qrc
