#!/bin/bash

function error()
{
    echo
    echo Error on line $1
    set -- $BASH_COMMAND
    if ! which $1 2>&1 > /dev/null 
    then
        echo Could not find command $1
    fi
    echo "Command \"$BASH_COMMAND\" failed"
    exit 1
}

trap 'error $LINENO $0' ERR

shopt -s expand_aliases

./qrc
qmake
make clean
make
cd ebedecl
make clean
make
cd ..
sudo cp ebe ebedecl/ebedecl /usr/bin
echo " "
echo ebe is now ready.  Type in \"ebe\" to run the program.
