#!/bin/bash

function error()
{
    echo
    echo Error on line $1
    set -- $BASH_COMMAND
    if ! which $1 2>&1 > /dev/null 
    then
        echo Could not find command $1
    fi
    echo "Command \"$BASH_COMMAND\" failed"
    exit 1
}

trap 'error $LINENO $0' ERR

./qrc
qmake
make clean
make -j 6
cd ebedecl
make clean
make
cd ..
pwd
name=$(uname -s )
if [ $name = Darwin ]
then
    if [ -x /usr/local/bin/brew ]
    then
        dest=/usr/local/bin
        cp ebedecl/ebedecl $dest
    elif [ -e /opt/local/bin ]
    then
        dest=/opt/local/bin
        sudo cp ebedecl/ebedecl $dest
    fi
    echo " "
    echo ebe is a script on Macs and can remain where it is.
    echo ebedecl has been copied to $dest
else
    dest=/usr/bin
    sudo cp ebe ebedecl/ebedecl $dest
    echo " "
    echo ebe and ebedecl have been copied to $dest
fi
echo " "
echo ebe is now ready.  Type in \"ebe\" to run the program.
